<#
.SYNOPSIS
Flags GetRuntimeData() call sites in project source that may need a REL::Module::IsVR()
gate, because their receiver's class also exposes a hand-written GetVRRuntimeData() that
returns a differently-laid-out struct (extra leading fields on VR).

.DESCRIPTION
CommonLibSSE-NG has two distinct GetRuntimeData() patterns:
  - SAFE (single accessor): generated by the RUNTIME_DATA_ACCESSOR macro, which picks the
    SE/VR byte offset internally via REL::RelocateMember(this, SEOffset, VROffset) and
    returns ONE struct type either way (e.g. RE::BSGraphics::Renderer::GetRuntimeData()).
    No caller-side branching needed.
  - DANGEROUS (hand-written pair): the class also declares GetVRRuntimeData(), returning a
    genuinely different struct type (VR has extra leading fields, so field offsets differ).
    GetRuntimeData()/GetVRRuntimeData() do NOT branch internally -- the CALLER must pick the
    right one via REL::Module::IsVR() / globals::game::isVR, or every field read/write
    silently lands on the wrong bytes. This exact gap caused a confirmed VR-only crash
    (investigate/effects11-vr, 2026-08-16): RendererShadowState and ImageSpaceManager call
    sites in Effects11 code called the flat accessor unconditionally.

This script auto-derives the "dangerous" class list from the CommonLibSSE-NG headers (any
class/struct whose own file declares GetVRRuntimeData()), resolves receiver names to that
list via explicit `RE::ClassName* name` declarations project-wide plus simple `auto x = y;`
alias propagation, then flags GetRuntimeData() calls on a resolved receiver with no
IsVR()/isVR nearby. It is a lint, not a prover: name-based receiver resolution can both miss
real cases (a receiver whose type never appears as an explicit `RE::Class*`/`&` declaration
anywhere, only ever behind `auto` with no traceable alias) and produce occasional false
positives (an unrelated local reusing a name like a dangerous class's), so a clean run is
not a proof and a flagged line still needs a human read before concluding it's a real bug.

.PARAMETER RepoRoot
Project root (default: parent of this script's directory).

.PARAMETER ContextLines
How many lines before/after a call site to search for an IsVR()/isVR gate (default 6).

.EXAMPLE
./tools/check-vr-runtime-data.ps1
#>
param(
    [string]$RepoRoot = (Split-Path -Parent $PSScriptRoot),
    [int]$ContextLines = 20
)

$commonLibInclude = Join-Path $RepoRoot "extern\CommonLibSSE-NG\include"
$srcRoot = Join-Path $RepoRoot "src"

if (-not (Test-Path $commonLibInclude)) {
    Write-Error "CommonLibSSE-NG include dir not found at $commonLibInclude"
    exit 1
}
if (-not (Test-Path $srcRoot)) {
    Write-Error "Project src dir not found at $srcRoot"
    exit 1
}

# --- Step 1: derive the dangerous class list from CommonLibSSE-NG headers ---
# Heuristic: CommonLibSSE-NG is one-primary-class-per-file; a header declaring
# GetVRRuntimeData() names its class the same as the file stem in the overwhelming
# majority of cases (confirmed: RendererShadowState.h, ImageSpaceManager.h, PlayerCamera.h,
# NiCamera.h, BSShaderAccumulator.h, BSShadowLight.h, ...). Excludes the macro-definition
# files themselves (RuntimeDataAccessors.h, Common.h), which are not classes.
$excludeFiles = @("RuntimeDataAccessors.h", "Common.h")
$dangerousFiles = Get-ChildItem -Path $commonLibInclude -Recurse -Filter "*.h" |
    Where-Object { $excludeFiles -notcontains $_.Name } |
    Where-Object { Select-String -Path $_.FullName -Pattern "GetVRRuntimeData" -Quiet }

$dangerousClasses = $dangerousFiles | ForEach-Object { $_.BaseName } | Sort-Object -Unique

Write-Host "Dangerous classes (declare GetVRRuntimeData, need caller-side IsVR gating):" -ForegroundColor Cyan
$dangerousClasses | ForEach-Object { Write-Host "  - $_" }
Write-Host ""

$sourceFiles = Get-ChildItem -Path $srcRoot -Recurse -Include "*.cpp", "*.h", "*.hpp"
$dangerousPattern = ($dangerousClasses | ForEach-Object { [regex]::Escape($_) }) -join "|"

# --- Step 2: resolve receiver names -> dangerous class, project-wide ---
# Pass A: explicit `RE::(...::)*ClassName [*&] name` declarations (globals, locals, params).
# Pass B: `auto name = <knownGlobalOrLocal>;` aliasing (this codebase's common idiom, e.g.
#   `auto shadowState = globals::game::shadowState;`) -- propagated by name, not scope, since
#   this is a lint (flag for review), not a real type resolution: a same-named local shadowing
#   an unrelated type would cause a false positive, which is an acceptable cost here.
$declPattern = "RE::(?:\w+::)*(?<cls>$dangerousPattern)\s*[*&]\s*(?<name>[A-Za-z_][A-Za-z0-9_]*)"
$receiverType = @{}
foreach ($file in $sourceFiles) {
    foreach ($line in (Get-Content -Path $file.FullName)) {
        foreach ($dm in [regex]::Matches($line, $declPattern)) {
            $receiverType[$dm.Groups["name"].Value] = $dm.Groups["cls"].Value
        }
    }
}
$aliasPattern = 'auto\s+(?<lhs>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?:[A-Za-z_][A-Za-z0-9_]*::)*(?<rhs>[A-Za-z_][A-Za-z0-9_]*)\s*;'
foreach ($file in $sourceFiles) {
    foreach ($line in (Get-Content -Path $file.FullName)) {
        $am = [regex]::Match($line, $aliasPattern)
        if ($am.Success -and $receiverType.ContainsKey($am.Groups["rhs"].Value) -and -not $receiverType.ContainsKey($am.Groups["lhs"].Value)) {
            $receiverType[$am.Groups["lhs"].Value] = $receiverType[$am.Groups["rhs"].Value]
        }
    }
}

Write-Host "Resolved $($receiverType.Count) receiver name(s) to a dangerous class." -ForegroundColor Cyan
Write-Host ""

# --- Step 3: scan project source for GetRuntimeData() call sites on resolved receivers ---
$callSitePattern = '(?<receiver>[A-Za-z_][A-Za-z0-9_]*)\s*(?:\.|->)\s*GetRuntimeData\s*\('
$vrGatePattern = 'IsVR\s*\(|(?<![A-Za-z0-9_])isVR(?![A-Za-z0-9_])'

$flagged = @()
foreach ($file in $sourceFiles) {
    $lines = Get-Content -Path $file.FullName
    for ($i = 0; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        $m = [regex]::Match($line, $callSitePattern)
        if (-not $m.Success) { continue }
        $receiver = $m.Groups["receiver"].Value
        if (-not $receiverType.ContainsKey($receiver)) { continue }

        $lo = [Math]::Max(0, $i - $ContextLines)
        $hi = [Math]::Min($lines.Count - 1, $i + $ContextLines)
        $context = ($lines[$lo..$hi] -join "`n")

        if ([regex]::IsMatch($context, $vrGatePattern)) { continue }

        $flagged += [PSCustomObject]@{
            File     = $file.FullName.Substring($RepoRoot.Length + 1)
            Line     = $i + 1
            Receiver = $receiver
            Class    = $receiverType[$receiver]
            Text     = $line.Trim()
        }
    }
}

if ($flagged.Count -eq 0) {
    Write-Host "No unguarded GetRuntimeData() call sites found." -ForegroundColor Green
    exit 0
}

Write-Host "Unguarded GetRuntimeData() call sites (no IsVR()/isVR within +/-$ContextLines lines):" -ForegroundColor Yellow
Write-Host "Review each: confirm the receiver's class isn't in the dangerous list above, or add an IsVR() branch." -ForegroundColor Yellow
Write-Host ""
foreach ($f in $flagged) {
    Write-Host "$($f.File):$($f.Line)" -ForegroundColor Red
    Write-Host "    receiver: $($f.Receiver) (RE::$($f.Class))"
    Write-Host "    $($f.Text)"
}

Write-Host ""
Write-Host "$($flagged.Count) flagged call site(s)." -ForegroundColor Yellow
exit 1
